export default {
  label: 'preferences.video.name',
  field: 'scrcpy',

  children: {
    noVideo: {
      label: 'preferences.video.noVideo.name',
      field: '--no-video',
      type: 'Switch',
      value: undefined,
      placeholder: 'preferences.video.noVideo.placeholder',
    },
    videoSource: {
      hidden: true,
      label: 'preferences.video.videoSource.name',
      field: '--video-source',
      type: 'Select',
      value: undefined,
      placeholder: 'preferences.video.videoSource.placeholder',
      options: [
        {
          label: 'preferences.video.videoSource.display',
          value: 'display',
        },
        {
          label: 'preferences.video.videoSource.camera',
          value: 'camera',
        },
      ],
    },
    // videoSource: {
    //   label: 'preferences.video.video-source.name',
    //   field: '--video-source',
    //   type: 'Select',
    //   value: undefined,
    //   placeholder: 'preferences.video.video-source.placeholder',
    //   options: [
    //     {
    //       label: 'preferences.video.video-source.display',
    //       value: 'display',
    //     },
    //     {
    //       label: 'preferences.video.video-source.camera',
    //       value: 'camera',
    //     },
    //   ],
    // },
    maxSize: {
      label: 'preferences.video.maxSize.name',
      field: '--max-size',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.video.maxSize.placeholder',
    },
    videoBitRate: {
      label: 'preferences.video.videoBitRate.name',
      field: '--video-bit-rate',
      type: 'Input',
      value: undefined,
      placeholder: 'preferences.video.videoBitRate.placeholder',
      append: 'bps',
    },
    maxFps: {
      label: 'preferences.video.maxFps.name',
      field: '--max-fps',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.video.maxFps.placeholder',
      append: 'fps',
    },
    videoCode: {
      hidden: 'global',
      label: 'preferences.video.videoCode.name',
      field: '--video-code',
      customized: true,
      type: 'VideoCodecSelect',
      value: undefined,
      placeholder: 'preferences.video.videoCode.placeholder',
      options: [
        {
          label: 'h264 & OMX.qcom.video.encoder.avc',
          value: 'h264 & OMX.qcom.video.encoder.avc',
        },
        {
          label: 'h264 & c2.android.avc.encoder',
          value: 'h264 & c2.android.avc.encoder',
        },
        {
          label: 'h264 & OMX.google.h264.encoder',
          value: 'h264 & OMX.google.h264.encoder',
        },
        {
          label: 'h265 & OMX.qcom.video.encoder.hevc',
          value: 'h265 & OMX.qcom.video.encoder.hevc',
        },
        {
          label: 'h265 & c2.android.hevc.encoder',
          value: 'h265 & c2.android.hevc.encoder',
        },
      ],
    },
    videoCodec: {
      hidden: true,
      field: '--video-codec',
      value: undefined,
    },
    videoEncoder: {
      hidden: true,
      field: '--video-encoder',
      value: undefined,
    },
    displayOrientation: {
      label: 'preferences.video.displayOrientation.name',
      field: '--display-orientation',
      type: 'Select',
      value: undefined,
      placeholder: 'preferences.video.displayOrientation.placeholder',
      options: [
        { label: '0°', value: '0' },
        { label: '90°', value: '90' },
        { label: '180°', value: '180' },
        { label: '270°', value: '270' },
        { label: 'flip-0°', value: 'flip0' },
        { label: 'flip-90°', value: 'flip90' },
        { label: 'flip-180°', value: 'flip180' },
        { label: 'flip-270°', value: 'flip270' },
      ],
    },
    angle: {
      label: 'preferences.video.angle.name',
      field: '--angle',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.video.angle.placeholder',
      tips: 'preferences.video.angle.tips',
      append: 'deg',
    },
    crop: {
      label: 'preferences.video.crop.name',
      field: '--crop',
      type: 'Select',
      value: undefined,
      placeholder: 'preferences.video.crop.placeholder',
      options: [
        { label: 'Full View', value: '' },
        { label: 'Quest 2 - 16x9', value: '1600:900:68:495' },
        { label: 'Quest 3 - 16x9', value: '1685:950:75:450' },
        { label: 'Quest 3 - 9x16', value: '1504:2008:300:200' },
        { label: 'Quest 3 - 1x1', value: '2064:2208:0:0' },
      ],
    },
    displayId: {
      hidden: 'global',
      label: 'preferences.video.displayId.name',
      field: '--display-id',
      type: 'DisplaySelect',
      value: undefined,
      placeholder: 'preferences.video.displayId.placeholder',
      options: [
        { label: '0', value: '0' },
      ],
    },
    anglePreset: {
      label: 'VR angle preset',
      field: '--angle',
      type: 'Select',
      value: undefined,
      placeholder: 'No angle preset',
      options: [
        { label: 'Quest 3', value: '22' },
        { label: 'None', value: '' },
      ],
    },
    videoBuffer: {
      label: 'preferences.video.videoBuffer.name',
      field: '--video-buffer',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.video.videoBuffer.placeholder',
      append: 'ms',
    },
    v4l2Buffer: {
      label: 'preferences.video.v4l2Buffer.name',
      field: '--v4l2-buffer',
      type: 'InputNumber',
      value: undefined,
      placeholder: 'preferences.video.v4l2Buffer.placeholder',
      append: 'ms',
    },
    // rotation: {
    //   label: 'Xoay hình (Cho Quest 3)',
    //   field: '--rotation-offset',
    //   type: 'Select',
    //   value: undefined,
    //   placeholder: 'Chỉ dành cho Quest 3',
    //   options: [
    //     { label: 'Quest 3', value: '22' },
    //     { label: 'Không xoay', value: '' },
    //   ],
    // },
    // positionx: {
    //   label: 'Vị trí X (Cho Quest 3)',
    //   field: '--position-x-offset',
    //   type: 'Select',
    //   value: undefined,
    //   placeholder: 'Chỉ dành cho Quest 3',
    //   options: [
    //     { label: 'Quest 3', value: '-110' },
    //     { label: 'Không chỉnh', value: '' },
    //   ],
    // },
    // positiony: {
    //   label: 'Vị trí Y (Cho Quest 3)',
    //   field: '--position-y-offset',
    //   type: 'Select',
    //   value: undefined,
    //   placeholder: 'Chỉ dành cho Quest 3',
    //   options: [
    //     { label: 'Quest 3', value: '-110' },
    //     { label: 'Không chỉnh', value: '' },
    //   ],
    // },
    // scale: {
    //   label: 'Phóng to (Cho Quest 3)',
    //   field: '--scale',
    //   type: 'Select',
    //   value: undefined,
    //   placeholder: 'Chỉ dành cho Quest 3',
    //   options: [
    //     { label: 'Quest 3', value: '135' },
    //     { label: 'Không chỉnh', value: '' },
    //   ],
    // },
    // displayId: {
    //   label: 'preferences.video.display.name',
    //   field: '--display-id',
    //   type: 'DisplaySelect',
    //   value: undefined,
    //   placeholder: 'preferences.video.display.placeholder',
    //   options: [
    //     { label: '0', value: '0' },
    //     { label: '1', value: '1' },
    //     { label: '2', value: '2' },
    //   ],
    //   props: {
    //     filterable: true,
    //     allowCreate: true,
    //   },
    // },
    // displayBuffer: {
    //   label: 'preferences.video.video-buffer.name',
    //   field: '--display-buffer',
    //   type: 'Input.number',
    //   value: undefined,
    //   placeholder: 'preferences.video.video-buffer.placeholder',
    //   append: 'ms',
    // },
    // v4l2Buffer: {
    //   label: 'preferences.video.receiver-buffer.name',
    //   field: '--v4l2-buffer',
    //   type: 'Input.number',
    //   value: undefined,
    //   placeholder: 'preferences.video.receiver-buffer.placeholder',
    //   append: 'ms',
    // },
  },
}
